# NumPy - Numerical Python Library

In [12]:
import numpy as np
from numpy import random

In [4]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

2

In [7]:
arr.shape

(2, 4)

In [8]:
arr.size

8

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr.data

# Random Numbers generation using arrays in NumPy

In [18]:
x=random.randint(1000)
x

607

In [22]:
y=random.rand()
y

0.6909810423916133

In [23]:
z=random.rand(5)
z

array([0.74065893, 0.47467515, 0.32639903, 0.50103242, 0.22787188])

In [24]:
m=random.randint(100, size=(5))
m

array([32,  6, 22, 26, 26])

In [25]:
m=random.randint(100, size=(5,3))
m

array([[51, 27, 94],
       [94, 74, 61],
       [23, 88, 27],
       [41, 34, 98],
       [14, 34, 67]])

In [26]:
m.ndim

2

In [29]:
p=random.randint(1000, size=(10))
p

array([519,  33, 357, 655, 838, 861, 123, 633, 315, 772])

In [30]:
q=random.randint(1000, size=(10))
q

array([553, 316, 583, 889, 862, 514, 123, 138, 909, 539])

In [31]:
r=p+q
r

array([1072,  349,  940, 1544, 1700, 1375,  246,  771, 1224, 1311])

In [33]:
r=p-q
r

array([ -34, -283, -226, -234,  -24,  347,    0,  495, -594,  233])

In [34]:
r=p*q
r

array([287007,  10428, 208131, 582295, 722356, 442554,  15129,  87354,
       286335, 416108])

In [35]:
r=q/p
r

array([1.0655106 , 9.57575758, 1.63305322, 1.35725191, 1.02863962,
       0.59698026, 1.        , 0.21800948, 2.88571429, 0.69818653])

In [36]:
print(r)

[1.0655106  9.57575758 1.63305322 1.35725191 1.02863962 0.59698026
 1.         0.21800948 2.88571429 0.69818653]


In [37]:
p/q

array([0.93851718, 0.10443038, 0.61234991, 0.7367829 , 0.97215777,
       1.67509728, 1.        , 4.58695652, 0.34653465, 1.432282  ])

# Creating Matrix in NumPy 

In [40]:
a=np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [41]:
#array-like input
b=np.matrix([[1,2,3],[4,5,0]])
b

matrix([[1, 2, 3],
        [4, 5, 0]])

# Measurement of Central Tendency using NumPy

In [47]:
ar=np.array([[1,23,78],[98,60,75],[79,25,48]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [49]:
ar.shape

(3, 3)

In [50]:
np.amin(ar)

1

In [51]:
np.amax(ar)

98

In [52]:
np.mean(ar)

54.111111111111114

In [53]:
np.median(ar)

60.0

In [54]:
np.std(ar) #standard deviation

30.296477405960523

In [55]:
np.var(ar) #Variance

917.8765432098766